"""Build menu.dishes UPDATE statements from the xlsx + dishes snapshot.

Emits ONLY the Section-2 confident auto-match updates (similarity >= HIGH in the
companion report). Run after reviewing tmp/ingest-report.md.

Usage:
    python3 scripts/menu/build_apply_sql.py \\
        --xlsx "/path/to/Приложение к меню.xlsx" \\
        --dishes-json tmp/dishes.json \\
        --out tmp/ingest-apply.sql

DOES NOT execute SQL — produces a file for human review and MCP-driven apply.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Reuse loaders + matching from the report script.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from ingest_xlsx_report import (  # type: ignore
    HIGH,
    load_dishes,
    load_xlsx,
    rank_candidates,
)


def sql_str(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def sql_int(n: int | None) -> str:
    return "NULL" if n is None else str(int(n))


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--xlsx", required=True, type=Path)
    p.add_argument("--dishes-json", required=True, type=Path)
    p.add_argument("--out", required=True, type=Path)
    args = p.parse_args()

    xlsx = load_xlsx(args.xlsx)
    dishes = load_dishes(args.dishes_json)
    by_id = {d.id: d for d in dishes}

    out: list[str] = []
    out.append("-- Auto-generated by scripts/menu/build_apply_sql.py")
    out.append("-- Section-2 confident xlsx matches (similarity >= %.2f)" % HIGH)
    out.append("BEGIN;")
    out.append("")

    applied = 0
    for x in xlsx:
        ranked = rank_candidates(x, dishes)
        if not ranked:
            continue
        score, top = ranked[0]
        if score < HIGH:
            continue
        # Compose the UPDATE.
        sets = [
            f"ingredients = {sql_str(x.ingredients)}",
            f"weight_g = {sql_int(x.weight_g)}",
            f"weight_label = {sql_str(x.weight_label)}",
            f"kcal_per_100g = {sql_int(x.kcal)}",
            f"protein_per_100g = {sql_int(x.protein)}",
            f"fat_per_100g = {sql_int(x.fat)}",
            f"carbs_per_100g = {sql_int(x.carbs)}",
            "ingredients_source = 'xlsx'",
            "nutrition_source = 'xlsx'",
            "updated_at = now()",
        ]
        out.append(f"-- xlsx#{x.idx} ({score:.2f}) {x.name}  →  {top.id} {top.name}")
        out.append(
            "UPDATE menu.dishes SET\n  " + ",\n  ".join(sets) +
            f"\nWHERE id = {sql_str(top.id)};"
        )
        out.append("")
        applied += 1

    # Bookkeeping row in import_runs.
    out.append(
        "INSERT INTO menu.import_runs(source, ran_at, rows_in, rows_matched, rows_inserted, notes) "
        f"VALUES ('xlsx_apply_v3', now(), {len(xlsx)}, {applied}, 0, "
        "'sect-2 confident matches, similarity >= 0.85; bumps sources to real');"
    )
    out.append("")
    out.append("COMMIT;")

    args.out.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"Wrote {args.out} — {applied} UPDATE statements.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
