import type { Category } from '@/lib/menu/types'

export type TargetDish = {
  id: string
  category: string
  name: string
  ingredients: string
  weight_g: number | null
  weight_label: string | null
  kcal: number | null
  protein: number | null
  fat: number | null
  carbs: number | null
}

export const targetCategories: Category[] = [
  { id: 'start', name: 'Старт', sort_order: 10 },
  { id: 'salads', name: 'Салаты', sort_order: 20 },
  { id: 'soups', name: 'Супы', sort_order: 30 },
  { id: 'burgers', name: 'Бургеры', sort_order: 40 },
  { id: 'mains', name: 'Основные', sort_order: 50 },
  { id: 'grill', name: 'Гриль', sort_order: 60 },
  { id: 'desserts', name: 'Десерты', sort_order: 70 },
]

// 73 positions extracted from data/nutrition_2026-05-23.xlsx
export const targetDishes: TargetDish[] = [
  {
    id: 'tgt-01-salatnyi-miks-s-tomatami',
    category: 'salads',
    name: 'Салатный микс с томатами',
    ingredients: 'Томаты, салатный микс, заправка из оливкового масла, дижонской горчицы и бальзамического крема, чеснок.',
    weight_g: 140,
    weight_label: '140 г',
    kcal: 115,
    protein: 1,
    fat: 11,
    carbs: 3,
  },
  {
    id: 'tgt-02-salat-iz-zapechennoi-svekly-s-syrom-sirtaki',
    category: 'salads',
    name: 'Салат из запеченной свеклы с сыром сиртаки',
    ingredients: 'Салатный микс,свекла, сыр сиртаки, кедовые орешки, дижонская горчица, оливковое масло, белый винный уксус, бальзамический крем,чеснок.',
    weight_g: 230,
    weight_label: '230 г',
    kcal: 205,
    protein: 3,
    fat: 19,
    carbs: 5,
  },
  {
    id: 'tgt-03-salat-iz-zapechennoi-svekly-s-kozim-syrom',
    category: 'salads',
    name: 'Салат из запеченной свеклы с козьим сыром',
    ingredients: 'Салатный микс,свекла, козий сыр, кедовые орешки, дижонская горчица, оливковое масло, белый винный уксус, бальзамический крем,чеснок.',
    weight_g: 230,
    weight_label: '230 г',
    kcal: 213,
    protein: 5,
    fat: 19,
    carbs: 5,
  },
  {
    id: 'tgt-04-grecheskii-salat',
    category: 'salads',
    name: 'Греческий салат',
    ingredients: 'Салатный микс, томаты, огурцы, болгарский перец, маслины, лук красный, оливковое масло, дижонская горчица, бальзамический крем, чеснок.',
    weight_g: 240,
    weight_label: '240 г',
    kcal: 132,
    protein: 2,
    fat: 12,
    carbs: 4,
  },
  {
    id: 'tgt-05-salat-s-tigrovymi-krevetkami-avokado-i-tomatami-cherr',
    category: 'salads',
    name: 'Салат с тигровыми креветками,авокадо и томатами черри',
    ingredients: 'Тигровые креветки, салатный микс, томаты черри, авокадо, цитрусовая заправка, чеснок, розмарин.',
    weight_g: 160,
    weight_label: '160 г',
    kcal: 128,
    protein: 6,
    fat: 10,
    carbs: 2,
  },
  {
    id: 'tgt-06-cezar-s-kuricei',
    category: 'salads',
    name: 'Цезарь с курицей',
    ingredients: 'Куриное филе, салат ромэйн, перепелиное яйцо, сыр пармезан, гренки, анчоусы, каперсы, сливки, соус ворчестер, бальзамический крем, чеснок.',
    weight_g: 175,
    weight_label: '175 г',
    kcal: 245,
    protein: 14,
    fat: 18,
    carbs: 5,
  },
  {
    id: 'tgt-07-cezar-s-krevetkami',
    category: 'salads',
    name: 'Цезарь с креветками',
    ingredients: 'Тигровые креветки, салат ромэйн, перепелиное яйцо, сыр пармезан, гренки, анчоусы, каперсы, сливки, соус ворчестер, бальзамический крем, чеснок.',
    weight_g: 175,
    weight_label: '175 г',
    kcal: 241,
    protein: 12,
    fat: 18,
    carbs: 5,
  },
  {
    id: 'tgt-08-cezar-s-lososem',
    category: 'salads',
    name: 'Цезарь с лососем',
    ingredients: 'Слабосоленый лосось, салат ромэйн, перепелиное яйцо, сыр пармезан, гренки, анчоусы, каперсы, сливки, соус ворчестер, бальзамический крем, чеснок, соевый соус.',
    weight_g: 175,
    weight_label: '175 г',
    kcal: 253,
    protein: 13,
    fat: 20,
    carbs: 5,
  },
  {
    id: 'tgt-09-bavarskii-salat-s-bekonom',
    category: 'salads',
    name: 'Баварский салат с беконом',
    ingredients: 'Бекон, куриное яйцо, маринованные огурцы, картофель по-деревенски, салат айсберг, салат романо, красный лук,сыр пармезан, майонез, баварская горчица.',
    weight_g: 265,
    weight_label: '265 г',
    kcal: 202,
    protein: 8,
    fat: 15,
    carbs: 5,
  },
  {
    id: 'tgt-10-kurinyi-sup-lapsha',
    category: 'soups',
    name: 'Куриный суп-лапша',
    ingredients: 'Куриное филе, куриный бульон, лапша, яйцо перепелиное, укроп, лавровый лист, черный перец горошком.',
    weight_g: 400,
    weight_label: '400 г',
    kcal: 101,
    protein: 7,
    fat: 5,
    carbs: 7,
  },
  {
    id: 'tgt-11-krem-sup-iz-tykvy-s-imbirem-i-tigrovymi-krevetkami',
    category: 'soups',
    name: 'Крем-суп из тыквы с имбирем и тигровыми креветками',
    ingredients: 'Тыква, жаренные тигровые креветки, картофель, сливки, оливковое масло, бальзамический крем, кориандр, корень имбиря, черный перец, гренки.',
    weight_g: 330,
    weight_label: '330 г',
    kcal: 150,
    protein: 3,
    fat: 13,
    carbs: 4,
  },
  {
    id: 'tgt-12-krem-sup-iz-shampinonov-s-syrom-i-grenkami',
    category: 'soups',
    name: 'Крем-суп из шампиньонов с сыром и гренками',
    ingredients: 'Шампиньоны, сыр пармезан, лук репчатый, сливки, мускатный орех,петрушка, черный перец, гренки.',
    weight_g: 400,
    weight_label: '400 г',
    kcal: 107,
    protein: 4,
    fat: 8,
    carbs: 4,
  },
  {
    id: 'tgt-13-borsch-s-borodinskimi-grenkami-i-salom',
    category: 'soups',
    name: 'Борщ с бородинскими гренками и салом',
    ingredients: 'Томленая говядина, говяжий бульон,картофель, капуста, свекла, морковь, лук репчатый,укроп, петрушка, чеснок / Шпик свиной,бородинский хлеб, зеленый лук, чеснок.',
    weight_g: null,
    weight_label: '450/75',
    kcal: 178,
    protein: 13,
    fat: 10,
    carbs: 9,
  },
  {
    id: 'tgt-14-harcho',
    category: 'soups',
    name: 'Харчо',
    ingredients: 'Томленая говядина, говяжий бульон, куриный бульон, рис, аджика, томатная паста, грецкий орех, кинза, петрушка.',
    weight_g: 400,
    weight_label: '400 г',
    kcal: 202,
    protein: 24,
    fat: 5,
    carbs: 10,
  },
  {
    id: 'tgt-15-okroshka-s-kuricei',
    category: 'soups',
    name: 'Окрошка с курицей',
    ingredients: 'Куриное филе, картофель, огурцы, редис, яйцо куриное, квас, майонез, сметана, хрен, горчица, зелень.',
    weight_g: 400,
    weight_label: '400 г',
    kcal: 77,
    protein: 4,
    fat: 5,
    carbs: 5,
  },
  {
    id: 'tgt-16-teisti-burger',
    category: 'burgers',
    name: 'Тейсти бургер',
    ingredients: 'Булочка, котлета из мраморной говядины, томаты, салат айсберг, красный лук, сыр эмменталь, фирменный соус, картофель фри.',
    weight_g: null,
    weight_label: '330/50/40',
    kcal: 160,
    protein: 8,
    fat: 7,
    carbs: 15,
  },
  {
    id: 'tgt-17-vagyu-burger',
    category: 'burgers',
    name: 'Вагю бургер',
    ingredients: 'Булочка, котлета из мраморной говядины сорта вагю,моцарелла, чеддер, красный лук, томаты, перечный соус.',
    weight_g: null,
    weight_label: '320/50/40',
    kcal: 140,
    protein: 5,
    fat: 7,
    carbs: 15,
  },
  {
    id: 'tgt-18-bbq-burger',
    category: 'burgers',
    name: 'BBQ бургер',
    ingredients: 'Булочка, котлета из мраморной говядины, хрустящий лук, бекон, салат айсберг, чеддер, моцарелла, маринованные огурцы, луковый мармелад, соус для бургеров, картофель фри.',
    weight_g: null,
    weight_label: '345/50/40',
    kcal: 202,
    protein: 10,
    fat: 10,
    carbs: 19,
  },
  {
    id: 'tgt-19-gribnoi-burger',
    category: 'burgers',
    name: 'Грибной бургер',
    ingredients: 'Булочка, котлета из мраморной говядины, моцарелла, сливочно-грибной соус, соус чесночный, маринованные огурцы, картофель фри.',
    weight_g: null,
    weight_label: '350/50/40',
    kcal: 191,
    protein: 11,
    fat: 10,
    carbs: 15,
  },
  {
    id: 'tgt-20-slou-burger',
    category: 'burgers',
    name: 'Слоу бургер',
    ingredients: 'Булочка, котлета из мраморной говядины, бекон, чеддер красный, пармезан, коул слоу, соус для бургера, картофель фри.',
    weight_g: null,
    weight_label: '360/50/40',
    kcal: 191,
    protein: 10,
    fat: 10,
    carbs: 14,
  },
  {
    id: 'tgt-21-ostryi-burger',
    category: 'burgers',
    name: 'Острый бургер',
    ingredients: 'Булочка, котлета из мраморной говядины,моцарелла. болгарский перец,  перец чили, халапеньо, маринованный лук, томатный соус, шрирача, картофель фри.',
    weight_g: null,
    weight_label: '355/50/40',
    kcal: 192,
    protein: 10,
    fat: 8,
    carbs: 19,
  },
  {
    id: 'tgt-22-demiglas',
    category: 'burgers',
    name: 'Демиглас',
    ingredients: 'Булочка, котлета из мраморной говядины, красный чеддер, моцарелла, красный лук, томаты, свежие огурцы, томатный соус, соус демиглас картофель фри.',
    weight_g: null,
    weight_label: '360/50/40',
    kcal: 160,
    protein: 9,
    fat: 7,
    carbs: 15,
  },
  {
    id: 'tgt-23-italyanskii-burger',
    category: 'burgers',
    name: 'Итальянский бургер',
    ingredients: 'Булочка, котлета из мраморной говядины, моцарелла, вяленые томаты, руккола, соус песто, томатный соус, картофель фри.',
    weight_g: null,
    weight_label: '310/50/40',
    kcal: 210,
    protein: 11,
    fat: 11,
    carbs: 17,
  },
  {
    id: 'tgt-24-chikenburger',
    category: 'burgers',
    name: 'Чикенбургер',
    ingredients: 'Булочка, котлета из куриного филе, томаты, салат айсберг, маринованный огурцы, красный лук, чеддер, томатный соус, соус для бургеров, картофель фри.',
    weight_g: null,
    weight_label: '340/50/40',
    kcal: 163,
    protein: 10,
    fat: 7,
    carbs: 15,
  },
  {
    id: 'tgt-25-francuzskii-burger',
    category: 'burgers',
    name: 'Французский бургер',
    ingredients: 'Булочка, котлета из мраморной говядины, моцарелла, чеддер, красный чеддер, сыр дорблю, салат айсберг, луковый мармелад, лук фри, соус с дижонской горчицей, картофель фри.',
    weight_g: null,
    weight_label: '350/50/40',
    kcal: 226,
    protein: 11,
    fat: 11,
    carbs: 19,
  },
  {
    id: 'tgt-26-chizburger',
    category: 'burgers',
    name: 'Чизбургер',
    ingredients: 'Булочка, котлета из мраморной говядины, чеддер, томаты, салат айсберг, маринованные огурцы, красный лук, томатный соус, соус для бургеров, картофель фри.',
    weight_g: null,
    weight_label: '340/50/40',
    kcal: 161,
    protein: 9,
    fat: 7,
    carbs: 16,
  },
  {
    id: 'tgt-27-mini-demiglas',
    category: 'burgers',
    name: 'Мини-демиглас',
    ingredients: 'Булочка, котлета из мраморной говядины, красный чеддер, моцарелла, красный лук, томаты, свежие огурцы, томатный соус, соус демиглас.',
    weight_g: 190,
    weight_label: '190 г',
    kcal: 176,
    protein: 11,
    fat: 9,
    carbs: 13,
  },
  {
    id: 'tgt-28-mini-italyanskii',
    category: 'burgers',
    name: 'Мини-итальянский',
    ingredients: 'Булочка, котлета из мраморной говядины, моцарелла, вяленые томаты, руккола, соус песто, томатный соус.',
    weight_g: 160,
    weight_label: '160 г',
    kcal: 223,
    protein: 12,
    fat: 13,
    carbs: 15,
  },
  {
    id: 'tgt-29-mini-francuzskii',
    category: 'burgers',
    name: 'Мини-французский',
    ingredients: 'Булочка, котлета из мраморной говядины, моцарелла, чеддер, красный чеддер, сыр дорблю, салат айсберг, луковый мармелад, лук фри, соус с дижонской горчицей.',
    weight_g: 180,
    weight_label: '180 г',
    kcal: 201,
    protein: 11,
    fat: 9,
    carbs: 19,
  },
  {
    id: 'tgt-30-mini-chikenburger',
    category: 'burgers',
    name: 'Мини-чикенбургер',
    ingredients: 'Булочка, котлета из куриного филе, томаты, салат айсберг, маринованный огурцы, красный лук, чеддер, томатный соус, соус для бургеров.',
    weight_g: 180,
    weight_label: '180 г',
    kcal: 144,
    protein: 12,
    fat: 4,
    carbs: 15,
  },
  {
    id: 'tgt-31-klab-sendvich-s-kurinym-file-bekonom-ovoschami-yaicom',
    category: 'start',
    name: 'Клаб-сэндвич с куриным филе,беконом,овощами  яйцом',
    ingredients: 'Хлебные тосты, куриное филе, бекон, томаты, красный лук, яйцо куриное, картофель фри, томатный соус, фирменный соус.',
    weight_g: 490,
    weight_label: '490 г',
    kcal: 167,
    protein: 9,
    fat: 8,
    carbs: 15,
  },
  {
    id: 'tgt-32-sendvich-s-buzheninoi-i-zernistoi-gorchicei',
    category: 'start',
    name: 'Сэндвич с бужениной и зернистой горчицей',
    ingredients: 'Хлебные тосты, буженина, салат айсберг, томаты, маринованный лук,сыр чеддер, сыр пармезан, горчица дижонская, майонез.',
    weight_g: 290,
    weight_label: '290 г',
    kcal: 233,
    protein: 9,
    fat: 15,
    carbs: 15,
  },
  {
    id: 'tgt-33-sendvich-s-krevetkami',
    category: 'start',
    name: 'Сэндвич с креветками',
    ingredients: 'Хлебные тосты,жаренные тигровые креветки ,сливочный сыр, салат айсберг, укроп, лайм,розмарин.',
    weight_g: 230,
    weight_label: '230 г',
    kcal: 167,
    protein: 9,
    fat: 7,
    carbs: 15,
  },
  {
    id: 'tgt-34-brusketta-s-rostbifom-vyalenymi-tomatami-i-sousom-pes',
    category: 'start',
    name: 'Брускетта с ростбифом, вялеными томатами и соусом песто',
    ingredients: 'Цельнозерновой багет, ростбиф,вяленые томаты, соус песто, микрозелень.',
    weight_g: 160,
    weight_label: '160 г',
    kcal: 232,
    protein: 14,
    fat: 14,
    carbs: 11,
  },
  {
    id: 'tgt-35-brusketta-s-lososem-slivochnym-syrom-i-avokado',
    category: 'start',
    name: 'Брускетта с лососем, сливочным сыром и авокадо',
    ingredients: 'Цельнозерновой багет, филе лосося с/с, авокадо, томаты черри, сливочный сыр, микрозелень.',
    weight_g: 210,
    weight_label: '210 г',
    kcal: 152,
    protein: 10,
    fat: 9,
    carbs: 8,
  },
  {
    id: 'tgt-36-govyazhi-schechki-s-kartofelnym-pyure-i-sousom-demigl',
    category: 'mains',
    name: 'Говяжьи щечки с картофельным пюре и соусом демиглас',
    ingredients: 'Томленые говяжьи щёки,картофельное пюре, соус демиглас, маринованные огурцы,лук фри.',
    weight_g: 390,
    weight_label: '390 г',
    kcal: 148,
    protein: 9,
    fat: 7,
    carbs: 12,
  },
  {
    id: 'tgt-37-befstroganov-s-kartofelnym-pyure',
    category: 'mains',
    name: 'Бефстроганов с картофельным пюре',
    ingredients: 'Говядина, шампиньоны, лук репчатый,сливки, розмарин, тимьян, чеснок, картофельное пюре, маринованные огурцы, микрозелень.',
    weight_g: 380,
    weight_label: '380 г',
    kcal: 171,
    protein: 7,
    fat: 13,
    carbs: 7,
  },
  {
    id: 'tgt-38-okorok-svinoi-v-pive-s-kartofelnym-pyure',
    category: 'mains',
    name: 'Окорок свиной в пиве с картофельным пюре',
    ingredients: 'Свиной окорок,томленый в пиве, картофельное пюре, огурцы маринованные, микрозелень.',
    weight_g: 360,
    weight_label: '360 г',
    kcal: 203,
    protein: 7,
    fat: 16,
    carbs: 8,
  },
  {
    id: 'tgt-39-buzhenina-s-marinovannym-lukom-i-zernistoi-gorchicei',
    category: 'mains',
    name: 'Буженина с маринованным луком и зернистой горчицей',
    ingredients: 'Буженина, маринованный лук, дижонская горчица, бальзамический крем, зелень.',
    weight_g: 210,
    weight_label: '210 г',
    kcal: 296,
    protein: 14,
    fat: 25,
    carbs: 5,
  },
  {
    id: 'tgt-40-pasta-boloneze',
    category: 'mains',
    name: 'Паста болоньезе',
    ingredients: 'Спагетти, фарш из свинины и говядины, сыр пармезан, лук репчатый , соус болоньезе, зелень.',
    weight_g: 340,
    weight_label: '340 г',
    kcal: 143,
    protein: 14,
    fat: 6,
    carbs: 12,
  },
  {
    id: 'tgt-41-pasta-karbonara',
    category: 'mains',
    name: 'Паста карбонара',
    ingredients: 'Спагетти,бекон, лук репчатый, сливки, сыр пармезан, яйцо куриное, мускат.',
    weight_g: 340,
    weight_label: '340 г',
    kcal: 223,
    protein: 14,
    fat: 13,
    carbs: 15,
  },
  {
    id: 'tgt-42-pasta-5-syrov',
    category: 'mains',
    name: 'Паста 5 сыров',
    ingredients: 'Фарфалле, сыр дор блю, сыр моцарелла, сыр пармезан, сыр чеддер, сыр чеддер красный, сливки, черный перец горошком.',
    weight_g: 300,
    weight_label: '300 г',
    kcal: 220,
    protein: 9,
    fat: 15,
    carbs: 13,
  },
  {
    id: 'tgt-43-pasta-s-tigrovymi-krevetkami-v-tomatnom-souse-s-bazil',
    category: 'mains',
    name: 'Паста с тигровыми креветками в томатном соусе с базиликом',
    ingredients: 'Спагетти, жаренные тигровые креветки, соус из протертых томатов,вяленые томаты, красный лук, чеснок, базилик, масло сливочное.',
    weight_g: 350,
    weight_label: '350 г',
    kcal: 122,
    protein: 12,
    fat: 4,
    carbs: 13,
  },
  {
    id: 'tgt-44-file-murmanskogo-lososya-na-grile',
    category: 'grill',
    name: 'Филе мурманского лосося на гриле',
    ingredients: 'Филе лосося на гриле / салатный микс, томаты.',
    weight_g: null,
    weight_label: '140/50',
    kcal: 173,
    protein: 14,
    fat: 6,
    carbs: 16,
  },
  {
    id: 'tgt-45-borodinskie-grenki-s-parmezanom-i-sousom-iz-smetany-i',
    category: 'start',
    name: 'Бородинские гренки с пармезаном и соусом из сметаны и каперсов',
    ingredients: 'Гренки из бородинского хлеба, сыр пармезан, чеснок / соус сметанный с каперсами.',
    weight_g: 150,
    weight_label: '150 г',
    kcal: 206,
    protein: 8,
    fat: 6,
    carbs: 31,
  },
  {
    id: 'tgt-46-kurinye-krylya-chipotl',
    category: 'start',
    name: 'Куриные крылья чипотл',
    ingredients: 'Жаренные куриные крылья, соус чипотл, чеснок, тимьян.',
    weight_g: 260,
    weight_label: '260 г',
    kcal: 216,
    protein: 17,
    fat: 15,
    carbs: 3,
  },
  {
    id: 'tgt-47-kurinye-krylya-bbq',
    category: 'start',
    name: 'Куриные крылья BBQ',
    ingredients: 'Жаренные куриные крылья, соус BBQ, чеснок, тимьян.',
    weight_g: 260,
    weight_label: '260 г',
    kcal: 194,
    protein: 16,
    fat: 14,
    carbs: 2,
  },
  {
    id: 'tgt-48-kurinye-krylya-sladkii-chili',
    category: 'start',
    name: 'Куриные крылья сладкий чили',
    ingredients: 'Жаренные куриные крылья, соус сладкий чили, чеснок, тимьян.',
    weight_g: 260,
    weight_label: '260 г',
    kcal: 225,
    protein: 16,
    fat: 14,
    carbs: 9,
  },
  {
    id: 'tgt-49-kurinye-krylya-teriyaki',
    category: 'start',
    name: 'Куриные крылья терияки',
    ingredients: 'Жаренные куриные крылья, соус терияки, чеснок, тимьян.',
    weight_g: 260,
    weight_label: '260 г',
    kcal: 209,
    protein: 16,
    fat: 5,
    carbs: 14,
  },
  {
    id: 'tgt-50-kartofel-fri',
    category: 'start',
    name: 'Картофель фри',
    ingredients: 'Картофель фри',
    weight_g: 140,
    weight_label: '140 г',
    kcal: 285,
    protein: 5,
    fat: 18,
    carbs: 27,
  },
  {
    id: 'tgt-51-kartofel-po-derevenski',
    category: 'start',
    name: 'Картофель по-деревенски',
    ingredients: 'Картофель по-деревенски дольками',
    weight_g: 140,
    weight_label: '140 г',
    kcal: 253,
    protein: 5,
    fat: 13,
    carbs: 28,
  },
  {
    id: 'tgt-52-lukovye-kolca-s-sousom-bbq',
    category: 'start',
    name: 'Луковые кольца с соусом BBQ',
    ingredients: 'Луковые кольца во фритюре, соус BBQ',
    weight_g: 140,
    weight_label: '140 г',
    kcal: 258,
    protein: 3,
    fat: 14,
    carbs: 28,
  },
  {
    id: 'tgt-53-kurinye-stripsy',
    category: 'start',
    name: 'Куриные стрипсы',
    ingredients: 'Куриное филе, яйцо куриное, панировка.',
    weight_g: 150,
    weight_label: '150 г',
    kcal: 215,
    protein: 23,
    fat: 5,
    carbs: 18,
  },
  {
    id: 'tgt-54-syrnye-shariki-s-brusnichnym-sousom',
    category: 'start',
    name: 'Сырные шарики с брусничным соусом',
    ingredients: 'Сыр моцарелла, сыр чеддер, панировка, яйцо куриное.',
    weight_g: 180,
    weight_label: '180 г',
    kcal: 234,
    protein: 14,
    fat: 15,
    carbs: 11,
  },
  {
    id: 'tgt-55-zharenye-tigrovye-krevetki',
    category: 'start',
    name: 'Жареные тигровые креветки',
    ingredients: 'Жаренные тигровые креветки, чеснок, розмарин, черри, лайм.',
    weight_g: 190,
    weight_label: '190 г',
    kcal: 111,
    protein: 13,
    fat: 4,
    carbs: 2,
  },
  {
    id: 'tgt-56-fish-end-chips-s-sousom-iz-smetany-i-kapersov',
    category: 'start',
    name: 'Фиш энд Чипс с соусом из сметаны и каперсов',
    ingredients: 'Филе судака в панировке / картофель фри / соус из сметаны и каперсов.',
    weight_g: null,
    weight_label: '180/50/40',
    kcal: 148,
    protein: 11,
    fat: 6,
    carbs: 14,
  },
  {
    id: 'tgt-57-seledochka-s-kartoshechkoi',
    category: 'start',
    name: 'Селедочка с картошечкой',
    ingredients: 'Филе сельди, отварной картофель, лук маринованный, конс. зеленый горошек.',
    weight_g: 300,
    weight_label: '300 г',
    kcal: 108,
    protein: 5,
    fat: 7,
    carbs: 7,
  },
  {
    id: 'tgt-58-solenya',
    category: 'start',
    name: 'Соленья',
    ingredients: 'Бекон, свиной шпик, маринованные : черемша, патиссоны, гурийская капуста, огурцы, чеснок, халапеньо',
    weight_g: 350,
    weight_label: '350 г',
    kcal: 225,
    protein: 4,
    fat: 21,
    carbs: 5,
  },
  {
    id: 'tgt-59-svinye-rebryshki-bbq',
    category: 'grill',
    name: 'Свиные ребрышки BBQ',
    ingredients: 'Свиные ребра, паприка, кориандр, соус BBQ.',
    weight_g: null,
    weight_label: '-',
    kcal: 330,
    protein: 16,
    fat: 28,
    carbs: 2,
  },
  {
    id: 'tgt-60-svinye-rebryshki-teriyaki',
    category: 'grill',
    name: 'Свиные ребрышки Терияки',
    ingredients: 'Свиные ребра, паприка, кориандр, соус терияки.',
    weight_g: null,
    weight_label: '-',
    kcal: 343,
    protein: 16,
    fat: 27,
    carbs: 8,
  },
  {
    id: 'tgt-61-svinye-rebryshki-chipotl',
    category: 'grill',
    name: 'Свиные ребрышки Чипотл',
    ingredients: 'Свиные ребра, паприка, кориандр, соус чипотл.',
    weight_g: null,
    weight_label: '-',
    kcal: 340,
    protein: 17,
    fat: 7,
    carbs: 27,
  },
  {
    id: 'tgt-62-govyazhi-rebryshki',
    category: 'grill',
    name: 'Говяжьи ребрышки',
    ingredients: 'Говяжьи ребра на гриле, томаты черри, розовый перец, розмарин.',
    weight_g: null,
    weight_label: '-',
    kcal: 198,
    protein: 12,
    fat: 3,
    carbs: 15,
  },
  {
    id: 'tgt-63-steik-striploin',
    category: 'grill',
    name: 'Стейк Стриплойн',
    ingredients: 'Стейк стриплойн на гриле, салатный микс, томаты черри.',
    weight_g: null,
    weight_label: '-',
    kcal: 226,
    protein: 16,
    fat: 18,
    carbs: 0,
  },
  {
    id: 'tgt-64-steik-ribai',
    category: 'grill',
    name: 'Стейк Рибай',
    ingredients: 'Стейк рибай на гриле, салатный микс, томаты черри.',
    weight_g: null,
    weight_label: '-',
    kcal: 265,
    protein: 21,
    fat: 10,
    carbs: 0,
  },
  {
    id: 'tgt-65-steik-file-minon',
    category: 'grill',
    name: 'Стейк Филе Миньон',
    ingredients: 'Стейк филе миньон на гриле, салатный микс, томаты черри.',
    weight_g: null,
    weight_label: '-',
    kcal: 145,
    protein: 20,
    fat: 7,
    carbs: 0,
  },
  {
    id: 'tgt-66-tushenaya-kapusta',
    category: 'mains',
    name: 'Тушеная капуста',
    ingredients: 'Капуста белокачанная, морковь, лук репчатый, соус из протертых томато, чеснок, лавровый лист.',
    weight_g: 200,
    weight_label: '200 г',
    kcal: 38,
    protein: 2,
    fat: 2,
    carbs: 5,
  },
  {
    id: 'tgt-67-kartofelnoe-pyure',
    category: 'mains',
    name: 'Картофельное пюре',
    ingredients: 'Картофель, молоко, масло сливочное.',
    weight_g: 150,
    weight_label: '150 г',
    kcal: 141,
    protein: 3,
    fat: 8,
    carbs: 13,
  },
  {
    id: 'tgt-68-grechka-s-gribami',
    category: 'mains',
    name: 'Гречка с грибами',
    ingredients: 'Греча, шампиньоны, белые грибы, лук репчатый, масло сливочное, тимьян.',
    weight_g: 150,
    weight_label: '150 г',
    kcal: 108,
    protein: 4,
    fat: 4,
    carbs: 16,
  },
  {
    id: 'tgt-69-ovoschi-gril',
    category: 'mains',
    name: 'Овощи гриль',
    ingredients: 'Перец болгарский, цуккини, баклажаны, шампиньоны, чеснок,тимьян, черный перец, масло оливковое.',
    weight_g: 150,
    weight_label: '150 г',
    kcal: 57,
    protein: 2,
    fat: 4,
    carbs: 4,
  },
  {
    id: 'tgt-70-brauni-s-keshyu-i-slivochnym-kremom',
    category: 'desserts',
    name: 'Брауни с кешью и сливочным кремом',
    ingredients: 'Мука пшенияная, яйцо куриное. масло сливочное, шоколад, сахар, орехи кешью, крем-чиз, сгущенное молоко, сливки, сахарная пудра.',
    weight_g: 160,
    weight_label: '160 г',
    kcal: 497,
    protein: 8,
    fat: 32,
    carbs: 45,
  },
  {
    id: 'tgt-71-chizkeik-san-sebastyan-na-pive',
    category: 'desserts',
    name: 'Чизкейк Сан-Себастьян на пиве',
    ingredients: 'Крем-чиз, яйцо куриное, сливки,сахар, пивной ганаш, молочный шоколад, мята.',
    weight_g: 170,
    weight_label: '170 г',
    kcal: 226,
    protein: 5,
    fat: 17,
    carbs: 14,
  },
  {
    id: 'tgt-72-yablochnyi-shtrudel-s-greckimi-orehami-i-vanilnym-plo',
    category: 'desserts',
    name: 'Яблочный штрудель с грецкими орехами и ванильным пломбиром',
    ingredients: 'Слоеное тесто, яблоки, сливки, грецкие орехи, сахар, корица, мороеное, мята, сливочный крем, сгущенное молоко.',
    weight_g: 340,
    weight_label: '340 г',
    kcal: 297,
    protein: 3,
    fat: 14,
    carbs: 39,
  },
  {
    id: 'tgt-73-morozhenoe',
    category: 'desserts',
    name: 'Мороженое',
    ingredients: 'Мороженое',
    weight_g: 150,
    weight_label: '150 г',
    kcal: 226,
    protein: 4,
    fat: 12,
    carbs: 26,
  },
]
